import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import type { RiskControl } from '@/lib/db/schema';

const styles = StyleSheet.create({
  page: { fontFamily: 'Helvetica', fontSize: 9, color: '#1a1a1a', padding: '40 50' },
  titlePage: { alignItems: 'center', justifyContent: 'center', flex: 1 },
  titleText: { fontSize: 22, fontFamily: 'Helvetica-Bold', marginBottom: 12, color: '#0d1b3e' },
  subtitleText: { fontSize: 13, color: '#555', marginBottom: 8 },
  metaText: { fontSize: 10, color: '#888', marginBottom: 4 },
  section: { marginTop: 20 },
  sectionTitle: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: '#0d1b3e', borderBottom: '1 solid #ddd', paddingBottom: 4, marginBottom: 10 },
  table: { width: '100%' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f0f4f8', borderBottom: '1 solid #d0d7e0', paddingVertical: 5 },
  tableRow: { flexDirection: 'row', borderBottom: '1 solid #eef0f3', paddingVertical: 4 },
  th: { fontFamily: 'Helvetica-Bold', fontSize: 7, color: '#555', textTransform: 'uppercase', paddingHorizontal: 4 },
  td: { fontSize: 8, paddingHorizontal: 4, color: '#222' },
  badge: { fontSize: 7, borderRadius: 3, paddingHorizontal: 4, paddingVertical: 2 },
  footer: { position: 'absolute', bottom: 30, left: 50, right: 50, textAlign: 'center', fontSize: 7, color: '#aaa' },
  summaryGrid: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  statBox: { flex: 1, padding: 10, backgroundColor: '#f8fafc', border: '1 solid #e2e8f0', borderRadius: 4 },
  statValue: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  statLabel: { fontSize: 7, color: '#666', textTransform: 'uppercase' },
  controlRow: { flexDirection: 'row', marginBottom: 4, padding: '4 6', backgroundColor: '#fafafa', border: '1 solid #eeeeee', borderRadius: 3 },
});

function rprBadgeColor(rpr: number | null): string {
  if (!rpr) return '#888888';
  if (rpr <= 4) return '#15803d';
  if (rpr <= 9) return '#b45309';
  return '#b91c1c';
}

interface HazardForPdf {
  id: string;
  number: number;
  description: string;
  harm?: string | null;
  hazardousSituation?: string | null;
  hazardCategory?: string | null;
  initialSeverity?: number | null;
  initialProbability?: number | null;
  initialRpr: number | null;
  mitigationMeasures?: string[] | null;
  residualSeverity?: number | null;
  residualProbability?: number | null;
  residualRpr: number | null;
  riskStatus: string;
  acceptability?: string | null;
  controls: RiskControl[];
}

interface RiskPdfDocumentProps {
  project: { name: string; deviceCategory: string; jurisdiction: string };
  device: { name: string; category: string; deviceClass?: string | null; intendedUse?: string | null; manufacturerName?: string | null } | null;
  hazards: HazardForPdf[];
  generatedAt: string;
}

export function RiskPdfDocument({ project, device, hazards, generatedAt }: RiskPdfDocumentProps) {
  const sorted = [...hazards].sort((a, b) => (b.initialRpr ?? 0) - (a.initialRpr ?? 0));
  const total = hazards.length;
  const open = hazards.filter(h => h.riskStatus === 'open').length;
  const mitigated = hazards.filter(h => h.riskStatus === 'mitigated').length;
  const accepted = hazards.filter(h => h.riskStatus === 'accepted').length;
  const unacceptable = hazards.filter(h => h.acceptability === 'unacceptable').length;
  const date = new Date(generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Column widths
  const COL = { num: 24, desc: 140, cat: 54, harm: 90, init: 42, mit: 100, res: 42, acc: 54, status: 42 };

  return (
    <Document>
      {/* Title page */}
      <Page size="A4" style={styles.page}>
        <View style={[styles.titlePage, { marginTop: 100 }]}>
          <Text style={styles.titleText}>Risk Management File</Text>
          <Text style={[styles.subtitleText, { fontSize: 11 }]}>ISO 14971:2019 Compliant</Text>
          <Text style={[styles.subtitleText, { marginTop: 20 }]}>{device?.name ?? project.name}</Text>
          {device?.manufacturerName && <Text style={styles.metaText}>Manufacturer: {device.manufacturerName}</Text>}
          {device?.deviceClass && <Text style={styles.metaText}>Device Class: {device.deviceClass}</Text>}
          <Text style={[styles.metaText, { marginTop: 12 }]}>Generated: {date}</Text>
          <Text style={[styles.metaText, { marginTop: 4, fontSize: 8, color: '#aaa' }]}>Generated by Maudie · ISO 14971:2019</Text>
        </View>
        <Text style={styles.footer} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
      </Page>

      {/* Summary page */}
      <Page size="A4" style={styles.page}>
        <Text style={[styles.sectionTitle, { fontSize: 14, marginBottom: 16, borderBottom: '2 solid #0d1b3e' }]}>
          Risk Management Summary
        </Text>

        <View style={styles.summaryGrid}>
          {[
            { label: 'Total Hazards', value: String(total), color: '#0d1b3e' },
            { label: 'Open', value: String(open), color: open > 0 ? '#b91c1c' : '#15803d' },
            { label: 'Mitigated', value: String(mitigated), color: '#15803d' },
            { label: 'Accepted', value: String(accepted), color: '#b45309' },
            { label: 'Unacceptable Risk', value: String(unacceptable), color: unacceptable > 0 ? '#b91c1c' : '#15803d' },
          ].map(s => (
            <View key={s.label} style={styles.statBox}>
              <Text style={[styles.statValue, { color: s.color }]}>{s.value}</Text>
              <Text style={styles.statLabel}>{s.label}</Text>
            </View>
          ))}
        </View>

        {device?.intendedUse && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Device Intended Use</Text>
            <Text style={{ fontSize: 9, color: '#333', lineHeight: 1.5 }}>{device.intendedUse}</Text>
          </View>
        )}

        <Text style={styles.footer} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
      </Page>

      {/* Hazard table page */}
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={[styles.sectionTitle, { fontSize: 12, marginBottom: 10 }]}>
          Risk Analysis — All Hazards (sorted by Initial RPR)
        </Text>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.th, { width: COL.num }]}>#</Text>
            <Text style={[styles.th, { width: COL.desc }]}>Description</Text>
            <Text style={[styles.th, { width: COL.cat }]}>Category</Text>
            <Text style={[styles.th, { width: COL.harm }]}>Harm</Text>
            <Text style={[styles.th, { width: COL.init }]}>Init RPR</Text>
            <Text style={[styles.th, { width: COL.mit }]}>Mitigations</Text>
            <Text style={[styles.th, { width: COL.res }]}>Res RPR</Text>
            <Text style={[styles.th, { width: COL.acc }]}>Accept.</Text>
            <Text style={[styles.th, { width: COL.status }]}>Status</Text>
          </View>

          {sorted.map((h) => (
            <View key={h.id} style={styles.tableRow} wrap={false}>
              <Text style={[styles.td, { width: COL.num, color: '#888' }]}>{h.number}</Text>
              <Text style={[styles.td, { width: COL.desc }]}>{h.description}</Text>
              <Text style={[styles.td, { width: COL.cat, color: '#555' }]}>
                {h.hazardCategory?.replace('_', ' ') ?? '—'}
              </Text>
              <Text style={[styles.td, { width: COL.harm, color: '#555' }]}>{h.harm ?? '—'}</Text>
              <Text style={[styles.td, { width: COL.init, color: rprBadgeColor(h.initialRpr), fontFamily: 'Helvetica-Bold' }]}>
                {h.initialRpr != null ? `${h.initialRpr} (${h.initialSeverity}×${h.initialProbability})` : '—'}
              </Text>
              <Text style={[styles.td, { width: COL.mit }]}>
                {h.mitigationMeasures?.join('; ') ?? (h.controls.length > 0 ? `${h.controls.length} control(s)` : '—')}
              </Text>
              <Text style={[styles.td, { width: COL.res, color: rprBadgeColor(h.residualRpr), fontFamily: 'Helvetica-Bold' }]}>
                {h.residualRpr != null ? `${h.residualRpr} (${h.residualSeverity}×${h.residualProbability})` : '—'}
              </Text>
              <Text style={[styles.td, { width: COL.acc, textTransform: 'capitalize' }]}>{h.acceptability ?? '—'}</Text>
              <Text style={[styles.td, { width: COL.status, textTransform: 'capitalize', color: h.riskStatus === 'open' ? '#b91c1c' : '#15803d' }]}>
                {h.riskStatus}
              </Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
      </Page>

      {/* Risk controls appendix */}
      {sorted.some(h => h.controls.length > 0) && (
        <Page size="A4" style={styles.page}>
          <Text style={[styles.sectionTitle, { fontSize: 12, marginBottom: 10 }]}>
            Appendix — Risk Controls
          </Text>

          {sorted.filter(h => h.controls.length > 0).map(h => (
            <View key={h.id} style={{ marginBottom: 14 }} wrap={false}>
              <Text style={{ fontSize: 9, fontFamily: 'Helvetica-Bold', marginBottom: 5 }}>
                H{h.number} — {h.description.length > 100 ? h.description.slice(0, 100) + '…' : h.description}
              </Text>
              {h.controls.map(c => (
                <View key={c.id} style={styles.controlRow}>
                  <Text style={{ width: 70, fontSize: 7, color: '#0d9488', textTransform: 'capitalize', fontFamily: 'Helvetica-Bold' }}>
                    {c.controlType}
                  </Text>
                  <Text style={{ flex: 1, fontSize: 8 }}>{c.description}</Text>
                  {c.verificationMethod && (
                    <Text style={{ width: 120, fontSize: 7, color: '#666' }}>Verify: {c.verificationMethod}</Text>
                  )}
                  <Text style={{ width: 50, fontSize: 7, color: c.verificationStatus === 'verified' ? '#15803d' : '#888', textTransform: 'capitalize' }}>
                    {c.verificationStatus ?? 'pending'}
                  </Text>
                </View>
              ))}
            </View>
          ))}

          <Text style={styles.footer} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
        </Page>
      )}
    </Document>
  );
}
